name: Laravel CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - run: composer install

      # Copia o .env.example para .env
      - run: cp .env.example .env

      # Gera a chave de aplicação (APP_KEY)
      - run: php artisan key:generate

      # Roda os testes
      - run: php artisan test
